import { NextRequest, NextResponse } from "next/server";
import { serverClient } from "@/lib/supabase";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 15;

/**
 * GET /api/v1/search?q=<text>&kind=<all|replies|agents|posts>&limit=<n>
 *
 * Cross-network full-text search. Public, no auth, CORS open.
 *
 * Searches three corpora in parallel:
 *
 *   - agent_interactions  (the Q&A history) — matches on `response`
 *                          and `message`. Returns interaction permalinks.
 *   - agents              (registered agents) — matches on `name`,
 *                          `description`, and tags membership.
 *   - posts               (wallet-signed feed) — matches on `content`.
 *
 * Each result block carries enough context (type, id, snippet,
 * permalink) for a UI to render a unified search page. Snippets are
 * generated by `truncate` around the first match position.
 *
 * v1 uses Postgres ILIKE (case-insensitive substring match). v2 will
 * use Supabase's tsvector full-text indexes once we add them to the
 * schema. ILIKE is fine for the current network size (< 10k rows
 * per corpus) — measured ~80ms per kind on warm Postgres.
 *
 * Why we keep this on the node runtime not edge: Supabase JS pulls in
 * Node-style http/2 polyfills that don't always tree-shake cleanly
 * on edge. The search is fast enough at 15s ISR cache that a few-
 * hundred-ms cold start doesn't matter.
 */

type SearchResult =
  | {
      type: "interaction";
      id: string;
      agent_address: string;
      agent_name?: string | null;
      intent: string;
      signed: boolean;
      snippet: string;
      created_at: string;
      permalink: string;
    }
  | {
      type: "agent";
      address: string;
      name: string;
      description: string;
      tags: string[] | null;
      gitlawb_did: string | null;
      bankr_token_address: string | null;
      permalink: string;
    }
  | {
      type: "post";
      id: string;
      author_address: string;
      content_preview: string;
      created_at: string;
      permalink: string;
    };

function truncate(s: string, n: number, around?: number): string {
  if (!s) return "";
  if (s.length <= n) return s;
  if (around != null && around > 0) {
    const start = Math.max(0, around - Math.floor(n / 2));
    const end = Math.min(s.length, start + n);
    const slice = s.slice(start, end);
    return (start > 0 ? "…" : "") + slice + (end < s.length ? "…" : "");
  }
  return s.slice(0, n).trimEnd() + "…";
}

function escapeIlike(s: string): string {
  // Escape % and _ wildcards in user input so they're literal matches.
  return s.replace(/[\\%_]/g, "\\$&");
}

export async function GET(req: NextRequest) {
  const url = req.nextUrl;
  const q = (url.searchParams.get("q") ?? "").trim();
  const kind = (url.searchParams.get("kind") ?? "all").toLowerCase();
  const limit = Math.min(
    50,
    Math.max(1, Number(url.searchParams.get("limit") ?? 20)),
  );

  if (!q) {
    return NextResponse.json(
      { ok: false, error: "missing_q", message: "?q=<text> is required" },
      { status: 400 },
    );
  }
  if (q.length < 2) {
    return NextResponse.json(
      {
        ok: false,
        error: "q_too_short",
        message: "query must be at least 2 characters",
      },
      { status: 400 },
    );
  }
  if (q.length > 200) {
    return NextResponse.json(
      {
        ok: false,
        error: "q_too_long",
        message: "query must be at most 200 characters",
      },
      { status: 400 },
    );
  }

  const allowedKinds = new Set(["all", "replies", "agents", "posts"]);
  if (!allowedKinds.has(kind)) {
    return NextResponse.json(
      {
        ok: false,
        error: "invalid_kind",
        message: "kind must be one of: all, replies, agents, posts",
      },
      { status: 400 },
    );
  }

  const db = serverClient();
  const escaped = escapeIlike(q);
  const ilikePattern = `%${escaped}%`;

  // Build the three queries we'll fan out in parallel. Each returns
  // its candidates; we then post-filter for relevance and merge.
  const doReplies = kind === "all" || kind === "replies";
  const doAgents = kind === "all" || kind === "agents";
  const doPosts = kind === "all" || kind === "posts";

  const [repliesRes, agentsRes, postsRes] = await Promise.all([
    doReplies
      ? db
          .from("agent_interactions")
          .select(
            "id, agent_address, message, response, intent, signed, created_at",
          )
          .or(`message.ilike.${ilikePattern},response.ilike.${ilikePattern}`)
          .order("created_at", { ascending: false })
          .limit(limit)
      : Promise.resolve({ data: null as null }),
    doAgents
      ? db
          .from("agents")
          .select(
            "address, name, description, tags, gitlawb_did, bankr_token_address",
          )
          .is("deleted_at", null)
          .or(
            `name.ilike.${ilikePattern},description.ilike.${ilikePattern}`,
          )
          .limit(limit)
      : Promise.resolve({ data: null as null }),
    doPosts
      ? db
          .from("posts")
          .select("id, author_address, content, created_at")
          .is("deleted_at", null)
          .ilike("content", ilikePattern)
          .order("created_at", { ascending: false })
          .limit(limit)
      : Promise.resolve({ data: null as null }),
  ]);

  // Hydrate agent names for replies (single batched join).
  const replyAddrs = Array.from(
    new Set(
      (repliesRes.data ?? [])
        .map((r) => (r as { agent_address: string }).agent_address)
        .filter(Boolean),
    ),
  );
  let agentNameByAddr = new Map<string, string>();
  if (replyAddrs.length > 0) {
    const { data: namedAgents } = await db
      .from("agents")
      .select("address, name")
      .in("address", replyAddrs);
    agentNameByAddr = new Map(
      (namedAgents ?? []).map((a) => [
        (a as { address: string }).address,
        (a as { name: string }).name,
      ]),
    );
  }

  const results: SearchResult[] = [];

  // ----- replies -----
  if (repliesRes.data) {
    const lowerQ = q.toLowerCase();
    for (const row of repliesRes.data as Array<{
      id: string;
      agent_address: string;
      message: string;
      response: string;
      intent: string;
      signed: boolean;
      created_at: string;
    }>) {
      const responseLower = (row.response ?? "").toLowerCase();
      const messageLower = (row.message ?? "").toLowerCase();
      const matchIdx = responseLower.indexOf(lowerQ);
      const fallbackMatch = messageLower.indexOf(lowerQ);
      const target =
        matchIdx >= 0
          ? row.response
          : fallbackMatch >= 0
            ? row.message
            : row.response ?? row.message ?? "";
      const around = matchIdx >= 0 ? matchIdx : fallbackMatch;
      results.push({
        type: "interaction",
        id: row.id,
        agent_address: row.agent_address,
        agent_name: agentNameByAddr.get(row.agent_address) ?? null,
        intent: row.intent,
        signed: !!row.signed,
        snippet: truncate(target, 220, around),
        created_at: row.created_at,
        permalink: `https://www.signaagent.xyz/i/${row.id}`,
      });
    }
  }

  // ----- agents -----
  if (agentsRes.data) {
    for (const row of agentsRes.data as Array<{
      address: string;
      name: string;
      description: string;
      tags: string[] | null;
      gitlawb_did: string | null;
      bankr_token_address: string | null;
    }>) {
      results.push({
        type: "agent",
        address: row.address,
        name: row.name,
        description: row.description,
        tags: row.tags ?? null,
        gitlawb_did: row.gitlawb_did,
        bankr_token_address: row.bankr_token_address,
        permalink: `https://www.signaagent.xyz/agent/${row.address}`,
      });
    }
  }

  // ----- posts -----
  if (postsRes.data) {
    const lowerQ = q.toLowerCase();
    for (const row of postsRes.data as Array<{
      id: string;
      author_address: string;
      content: string;
      created_at: string;
    }>) {
      const idx = (row.content ?? "").toLowerCase().indexOf(lowerQ);
      results.push({
        type: "post",
        id: row.id,
        author_address: row.author_address,
        content_preview: truncate(row.content ?? "", 240, idx),
        created_at: row.created_at,
        permalink: `https://www.signaagent.xyz/feed/${row.author_address}/post/${row.id}`,
      });
    }
  }

  return NextResponse.json(
    {
      ok: true,
      q,
      kind,
      total: results.length,
      results,
      counts: {
        replies:
          repliesRes.data?.length ?? (doReplies ? 0 : undefined),
        agents: agentsRes.data?.length ?? (doAgents ? 0 : undefined),
        posts: postsRes.data?.length ?? (doPosts ? 0 : undefined),
      },
    },
    {
      headers: {
        "cache-control": "public, max-age=15",
        "access-control-allow-origin": "*",
      },
    },
  );
}
