#!/usr/bin/env bash
# signa CLI installer — v0.2
# Usage:  curl -fsSL https://www.signaagent.xyz/install.sh | bash
#
# Lays down:
#   ~/.signa/signa.mjs           the CLI source
#   ~/.signa/package.json        declares viem as a dep
#   ~/.signa/node_modules/viem/  pulled by npm install
#   ~/.signa/bin/signa           POSIX shell wrapper → node ~/.signa/signa.mjs "$@"
#
# Idempotent. Re-running upgrades signa.mjs in place and refreshes deps.

set -euo pipefail

BASE_URL="${SIGNA_BASE_URL:-https://www.signaagent.xyz}"
SIGNA_HOME="$HOME/.signa"
BIN_DIR="$SIGNA_HOME/bin"
BIN_PATH="$BIN_DIR/signa"
CLI_PATH="$SIGNA_HOME/signa.mjs"
PKG_PATH="$SIGNA_HOME/package.json"
SOURCE_URL="$BASE_URL/signa.mjs"

# ---------- prereqs ----------

if ! command -v node >/dev/null 2>&1; then
  cat <<EOF >&2

signa needs Node.js (18 or newer). install it first:

  macOS / Linux:  curl -fsSL https://fnm.vercel.app/install | bash && fnm install 20
  or:             https://nodejs.org/en/download

then re-run this installer.

EOF
  exit 1
fi

NODE_MAJOR="$(node -e 'console.log(process.versions.node.split(".")[0])')"
if [ "$NODE_MAJOR" -lt 18 ]; then
  echo >&2 "signa needs Node 18 or newer. you have $(node -v)."
  echo >&2 "upgrade Node and re-run this installer."
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo >&2 "✗ npm is required to fetch wallet deps (viem). install npm (ships with Node.js) and re-run."
  exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
  echo >&2 "curl is required. install it and re-run."
  exit 1
fi

# ---------- layout ----------

mkdir -p "$SIGNA_HOME" "$BIN_DIR"

# ---------- download CLI source ----------

echo "↓ downloading signa.mjs from $SOURCE_URL"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
curl -fsSL -o "$TMP" "$SOURCE_URL"
mv "$TMP" "$CLI_PATH"
chmod 644 "$CLI_PATH"

# ---------- declare deps + install ----------

# We pin viem to a major to avoid silent breakage. The CLI dynamic-imports
# 'viem', 'viem/accounts', and 'viem/chains' — all stable since viem 2.0.
cat > "$PKG_PATH" <<'EOF'
{
  "name": "signa-cli-runtime",
  "version": "0.3.0",
  "private": true,
  "description": "Local dep bag for the signa CLI. Don't edit by hand.",
  "type": "module",
  "dependencies": {
    "viem": "^2.21.0",
    "@xmtp/node-sdk": "^4.0.0"
  }
}
EOF

echo "↓ installing viem + @xmtp/node-sdk into $SIGNA_HOME/node_modules (one-time, ~30s)"
echo "  (xmtp pulls native crypto bindings — first install is the slowest)"
(
  cd "$SIGNA_HOME"
  # --silent keeps the installer output clean. --no-audit + --no-fund skip
  # the chatty network calls. --no-package-lock so we don't litter a lock
  # the user didn't ask for.
  npm install --silent --no-audit --no-fund --no-package-lock >/dev/null
)

# ---------- bin wrapper ----------

cat > "$BIN_PATH" <<EOF
#!/usr/bin/env bash
# signa wrapper — generated by install.sh
exec node "$CLI_PATH" "\$@"
EOF
chmod +x "$BIN_PATH"

# ---------- verify ----------

if ! "$BIN_PATH" version >/dev/null 2>&1; then
  echo >&2 "✗ installed binary failed self-check. try re-running the installer."
  exit 1
fi

VERSION="$("$BIN_PATH" version 2>/dev/null || echo "v?")"

# ---------- PATH guidance ----------

cat <<EOF

✓ signa installed at $BIN_PATH
✓ $VERSION
✓ viem installed at $SIGNA_HOME/node_modules/viem

add ~/.signa/bin to your PATH so you can run \`signa\` from anywhere.

  bash / zsh:
    echo 'export PATH="\$HOME/.signa/bin:\$PATH"' >> ~/.zshrc
    source ~/.zshrc

  fish:
    fish_add_path ~/.signa/bin

then try:
  signa --help
  signa ask "price of \\\$USDC on base"
  signa login --new
  signa wallet
  signa post "hello from the signa cli"
  signa inbox

decentralized cli for the signa network. base mainnet.
EOF
