[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 2_000_000

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api" }

[fmt]
line_length = 100
tab_width = 4
quote_style = "double"
