"use client";

import { useState } from "react";
import { Loader2, Sparkles, ExternalLink } from "lucide-react";

/**
 * Public-facing "try this agent" widget — embedded on /agent/[address].
 *
 * Lets anyone (no wallet, no signin) ask a SIGNA agent a real question and
 * see a real Groq-synthesized reply with cited sources. Hits the same
 * `POST /api/agents/[address]/respond` endpoint that third-party clients
 * use, so this widget IS the demo of the primitive.
 *
 * Why this matters:
 *   - Non-coders can verify the agent actually works (they can see
 *     responses, citations, intent classification, signing status).
 *   - It doubles as the "stage" for the agent — a public square anyone
 *     who lands on a /agent/<addr> URL can interact with.
 *   - Each question persists into `agent_interactions` for future
 *     reputation scoring.
 */

type Source = { kind: string; ref: string };

type RespondJson = {
  ok: boolean;
  response?: string;
  intent?: string;
  sources?: Source[];
  signed?: boolean;
  signature?: string | null;
  signed_message?: string | null;
  agent_did?: string | null;
  interaction_id?: string | null;
  notice?: string | null;
  error?: string;
  message?: string;
};

const PRESETS: { label: string; prompt: string; intent: string }[] = [
  {
    label: "$USDC price",
    intent: "facts",
    prompt:
      "what is the price of $USDC on base? 0x833589fcd6edb6e08f4c7c32d4f71b54bda02913",
  },
  {
    label: "build a dashboard",
    intent: "code",
    prompt: "build me a small single-html dashboard for base trending tokens",
  },
  {
    label: "simulate a swarm",
    intent: "swarm",
    prompt: "simulate a swarm of 1000 wallets buying $AEON over 24h",
  },
  {
    label: "who are you",
    intent: "chat",
    prompt: "who are you and what can you do?",
  },
];

const INTENT_COLOR: Record<string, string> = {
  facts: "text-cyan-300 border-cyan-400/30 bg-cyan-400/[0.04]",
  code: "text-violet-300 border-violet-400/30 bg-violet-400/[0.04]",
  swarm: "text-amber-300 border-amber-400/30 bg-amber-400/[0.04]",
  action: "text-rose-300 border-rose-400/30 bg-rose-400/[0.04]",
  chat: "text-emerald-300 border-emerald-400/30 bg-emerald-400/[0.04]",
  error: "text-red-300 border-red-400/30 bg-red-400/[0.04]",
};

export function AgentRespondWidget({
  address,
  agentName,
}: {
  address: string;
  agentName: string;
}) {
  const [message, setMessage] = useState("");
  const [reply, setReply] = useState<RespondJson | null>(null);
  const [busy, setBusy] = useState(false);
  const [elapsedMs, setElapsedMs] = useState<number | null>(null);

  async function ask(promptOverride?: string) {
    const m = (promptOverride ?? message).trim();
    if (!m || busy) return;
    setBusy(true);
    setReply(null);
    setElapsedMs(null);
    const t0 = performance.now();
    try {
      const res = await fetch(`/api/agents/${address.toLowerCase()}/respond`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ message: m }),
      });
      const j = (await res.json()) as RespondJson;
      setReply(j);
    } catch (e) {
      setReply({
        ok: false,
        error: "network_error",
        message: e instanceof Error ? e.message : String(e),
      });
    } finally {
      setElapsedMs(Math.round(performance.now() - t0));
      setBusy(false);
    }
  }

  function onPreset(p: (typeof PRESETS)[number]) {
    setMessage(p.prompt);
    void ask(p.prompt);
  }

  return (
    <section className="border-b border-white/[0.06]">
      <div className="max-w-3xl mx-auto px-6 lg:px-10 py-10">
        <div className="font-mono text-[11px] text-[var(--accent)] mb-3">
          $ signa agent respond --address {address.slice(0, 10)}…
        </div>

        <div className="border border-white/10 bg-black/30 p-4">
          <div className="text-white/65 text-[13px] leading-relaxed mb-3">
            Ask <span className="text-white font-medium">{agentName}</span> a
            question. Replies are generated by{" "}
            <span className="font-mono text-white/80">
              POST /api/agents/{address.slice(0, 8)}…/respond
            </span>
            {" "}— a public, no-auth endpoint that routes facts→Bankr+
            GeckoTerminal, swarm→MiroShark, code→gitlawb Playground,
            action→Bankr, chat→Groq. Every reply lands in our{" "}
            <span className="font-mono text-white/80">agent_interactions</span>{" "}
            table for replay + reputation.
          </div>

          {/* Quick presets */}
          <div className="flex flex-wrap gap-1.5 mb-3">
            {PRESETS.map((p) => (
              <button
                key={p.label}
                disabled={busy}
                onClick={() => onPreset(p)}
                className="text-[11px] font-mono border border-white/15 text-white/70 hover:text-white hover:bg-white/[0.04] px-2 py-1 rounded-sm transition disabled:opacity-40"
              >
                {p.label}
              </button>
            ))}
          </div>

          {/* Composer */}
          <textarea
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            placeholder={`ask ${agentName} anything…`}
            rows={3}
            maxLength={1500}
            disabled={busy}
            className="w-full bg-black/40 border border-white/15 text-white text-[14px] p-3 font-mono rounded-sm placeholder:text-white/30 focus:outline-none focus:border-[var(--accent)]/60 resize-y disabled:opacity-50"
          />
          <div className="flex items-center justify-between mt-2">
            <div className="text-[10px] text-white/35 font-mono">
              {message.length}/1500 · free · CORS-open · public
            </div>
            <button
              onClick={() => ask()}
              disabled={busy || !message.trim()}
              className="bg-[var(--accent)] text-black font-semibold text-[12px] uppercase tracking-wide rounded-sm px-3 py-1.5 inline-flex items-center gap-1.5 hover:brightness-110 transition disabled:opacity-40"
            >
              {busy ? (
                <Loader2 className="size-3 animate-spin" />
              ) : (
                <Sparkles className="size-3" />
              )}
              {busy ? "thinking…" : "ask"}
            </button>
          </div>
        </div>

        {/* Reply */}
        {reply && (
          <div className="mt-4 border border-white/10 bg-black/30 p-4">
            <div className="flex items-center gap-2 mb-3 flex-wrap">
              {reply.intent && (
                <span
                  className={`text-[10px] uppercase tracking-wider font-mono border rounded-sm px-1.5 py-0.5 ${INTENT_COLOR[reply.intent] ?? INTENT_COLOR.chat}`}
                >
                  intent: {reply.intent}
                </span>
              )}
              {reply.signed === true ? (
                <span className="text-[10px] uppercase tracking-wider font-mono border border-emerald-400/30 bg-emerald-400/[0.04] text-emerald-300 rounded-sm px-1.5 py-0.5">
                  ✓ signed by agent
                </span>
              ) : reply.ok ? (
                <span className="text-[10px] uppercase tracking-wider font-mono border border-white/15 text-white/55 rounded-sm px-1.5 py-0.5">
                  unsigned (non-custodial agent)
                </span>
              ) : null}
              {elapsedMs != null && (
                <span className="text-[10px] font-mono text-white/35 ml-auto">
                  {elapsedMs}ms
                </span>
              )}
            </div>

            {reply.ok && reply.response ? (
              <pre className="text-[13px] text-white whitespace-pre-wrap leading-relaxed font-sans">
                {reply.response}
              </pre>
            ) : (
              <pre className="text-[12px] text-red-300 whitespace-pre-wrap font-mono">
                {reply.error ?? "error"}: {reply.message ?? "(no detail)"}
              </pre>
            )}

            {/* Sources */}
            {reply.sources && reply.sources.length > 0 && (
              <div className="mt-4 pt-3 border-t border-white/[0.06]">
                <div className="text-[10px] uppercase tracking-wider text-white/35 mb-1.5 font-mono">
                  sources cited
                </div>
                <ul className="space-y-1">
                  {reply.sources.map((s, i) => (
                    <li
                      key={i}
                      className="text-[11px] font-mono text-white/70 flex items-center gap-2"
                    >
                      <span className="text-[var(--accent)]">{s.kind}</span>
                      <span className="text-white/40">·</span>
                      <span className="text-white/65 truncate">{s.ref}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Verifiable trail */}
            {reply.interaction_id && (
              <div className="mt-3 text-[10px] font-mono text-white/35">
                interaction_id: {reply.interaction_id}
              </div>
            )}

            {/* Notice */}
            {reply.notice && (
              <div className="mt-3 text-[10px] font-mono text-white/45 italic">
                {reply.notice}
              </div>
            )}

            {/* Try it yourself link */}
            <div className="mt-4 pt-3 border-t border-white/[0.06] flex items-center gap-2 flex-wrap">
              <a
                href={`/api/agents/${address.toLowerCase()}/respond`}
                target="_blank"
                rel="noreferrer"
                className="text-[11px] font-mono text-white/55 hover:text-white inline-flex items-center gap-1 underline underline-offset-4"
              >
                view endpoint schema
                <ExternalLink className="size-2.5" />
              </a>
              <span className="text-white/25 text-[11px]">·</span>
              <code className="text-[10px] font-mono text-white/50 bg-white/[0.03] px-1.5 py-0.5 rounded-sm">
                curl -X POST signaagent.xyz/api/agents/{address.slice(0, 6)}…/respond
              </code>
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
